FROM datadog/agent:latest
ADD etc/datadog/conf.d/spark.d/conf.yaml /etc/datadog-agent/conf.d/spark.d/conf.yaml
ADD etc/datadog/conf.d/network.d/conf.yaml /etc/datadog-agent/conf.d/network.d/conf.yaml
